<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Macros -->
    <xacro:property name="arm_base_length" value="0.1"/>
    <xacro:property name="arm_base_width" value="0.1"/>
    <xacro:property name="arm_base_height" value="0.02"/>
    <xacro:property name="arm_radius" value="0.02"/>
    <xacro:property name="arm_length" value="0.3"/>

    <!-- Arm Base Link -->
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <material name="orange"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
    </link>

    <!-- Forearm link -->
    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"/>
            </geometry>
            <material name="yellow"/>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </visual>
    </link>

    <!-- Joint between arm_base_link and forearm_link -->
    <joint name="arm_base_link_forearm_link_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics friction="0.05" damping="0.1"/>
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100"/>
    </joint>

    <!-- Hand Link -->
    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"/>
            </geometry>
            <material name="orange"/>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </visual>
    </link>

    <!-- Joint between forearm_link and hand_link -->
    <joint name="forearm_link_hand_link_joint" type="revolute">
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics friction="0.05" damping="0.1"/>
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100"/>
    </joint>
</robot>