<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Camera Link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.025 0.05 0.05"/>
            </geometry>
            <material name="red"/>
            <orgin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.025 0.05 0.05"/>
            </geometry>
            <orgin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="0.5" l="0.025" w="0.05" h="0.05" xyz="0 0 0" rpy="0 0 0"/>
    </link>
    <!-- Joint between base and camera -->
    <joint name="base_link_camera_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${(base_length+0.025)/2} 0 ${base_height/2}" rpy="0 0 0"/>
    </joint>
    <!-- Gazebo Color -->
    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera_sensor" type="camera">
            <pose> 0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <plugin name="camera_plugin" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>